name: Fly Deploy

on:
  workflow_run:
    workflows: ["Extract data"]
    types:
      - completed

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --build-secret OPENAI_API_KEY=$OPENAI_API_KEY --remote-only --no-cache
