name: Fly Deploy

on:
  schedule:
    - cron: '0 */13 * * *' # https://crontab.guru/#0_*/20_*_*_* '0 */12 * * *'
    
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: flyctl deploy --build-secret OPENAI_API_KEY=$OPENAI_API_KEY --remote-only
